import './globals.css';
import Navbar from './components/Navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang='en'>
   <body className='dark:bg-slate-800'>
    <main className='px-4 md:px-6 prose prose-xl prose-slate dark:prose-invert'>
     {children}
    </main>
   </body>
  </html>
 );
}
